### ISSUE TITLE
indi server のみを RaspberryOS に構築して、ネットワークから遠隔操作する

### ISSUE THREAD

**Issue by denebola213** [denebola213/web-pages#6]
https://docs.indilib.org/indiserver/

```
sudo apt-get install -y \
  git \
  cdbs \
  dkms \
  cmake \
  ninja-build \
  fxload \
  libev-dev \
  libgps-dev \
  libgsl-dev \
  libraw-dev \
  libusb-dev \
  zlib1g-dev \
  libftdi-dev \
  libjpeg-dev \
  libkrb5-dev \
  libnova-dev \
  libtiff-dev \
  libfftw3-dev \
  librtlsdr-dev \
  libcfitsio-dev \
  libgphoto2-dev \
  build-essential \
  libusb-1.0-0-dev \
  libdc1394-dev \
  libboost-regex-dev \
  libcurl4-gnutls-dev \
  libtheora-dev \
  libxisf-dev \
  liberfa-dev

git clone --depth 1 https://github.com/indilib/indi.git
cd indi
./developer-build.bash
cd build
sudo make install
```

**Comment by denebola213** [comment]
# 3rd party のドライバ: https://github.com/indilib/indi-3rdparty

```
sudo apt-get -y install libnova-dev libcfitsio-dev libusb-1.0-0-dev zlib1g-dev libgsl-dev build-essential cmake git libjpeg-dev libcurl4-gnutls-dev libtiff-dev libfftw3-dev libftdi-dev libgps-dev libraw-dev libdc1394-dev libgphoto2-dev libboost-dev libboost-regex-dev librtlsdr-dev liblimesuite-dev libftdi1-dev libavcodec-dev libavdevice-dev libzmq3-dev libudev-dev libzmq3-dev

git clone --depth=1 https://github.com/indilib/indi-3rdparty
```

## install libsvbony

```bash
mkdir -p ~/build/libsvbony  && cd ~/build/libsvbony
cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug ~/indi-3rdparty/libsvbony
make -j4
sudo make install
```

## install indi-svbony

```bash
mkdir -p ~/build/indi-svbony && cd ~/build/indi-svbony

cmake -DCMAKE_INSTALL_PREFIX=/usr ~/indi-3rdparty/indi-svbony
make
sudo make install
```

## install libplayerone

```bash
mkdir -p ~/build/libplayerone && cd ~/build/libplayerone
cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug ~/indi-3rdparty/libplayerone
make -j4
sudo make install
```

## install indi-playerone

```bash
mkdir -p ~/build/indi-playerone && cd ~/build/indi-playerone

cmake -DCMAKE_INSTALL_PREFIX=/usr ~/indi-3rdparty/indi-playerone
make
sudo make install
```

**Comment by denebola213** [comment]
libsvbony をビルドすることで解消

```sh
mkdir -p ~/Projects/build/libsvbony && cd ~/Projects/build/libsvbony
cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug ~/Projects/indi-3rdparty/libsvbony
make -j4
sudo make install
```

**Comment by denebola213** [comment]
indi-playerone インストール時のエラー
```sh
CMake Error at /home/denebola213/Projects/indi-3rdparty/cmake_modules/FindPLAYERONE.cmake:55 (message):
  PLAYERONE not found.  Please install libPlayerOneCamera.3
  http://www.indilib.org
Call Stack (most recent call first):
  CMakeLists.txt:8 (find_package)
```

libplayerone をビルドすることで解消

mkdir -p ~/Projects/build/libplayerone && cd ~/Projects/build/libplayerone
cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug ~/Projects/indi-3rdparty/libplayerone
make -j4
sudo make install

**Comment by denebola213** [comment]
indiweb 必要

python3.12以下でないと cgi モジュールがないため、 pyenvでインストールする
python3.12以下でないと cgi モジュールがないため、 pyenvでインストールする

```bash
curl -fsSL https://pyenv.run | bash

echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
echo '[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
echo 'eval "$(pyenv init - bash)"' >> ~/.bashrc

sudo apt update
sudo apt install libsqlite3-dev
pyenv install 3.12
```

Ubuntu24では `pip install` が使えないため以下のリンクの通りpipenvを使う
https://github.com/knro/indiwebmanager/issues/59#issuecomment-2327044696

```bash
sudo apt install pipenv

mkdir ~/indiweb && cd ~/indiweb
pipenv --python=`which python3.12`
pipenv install indiweb
pipenv run indi-web -v
```

systemd の service file を作成する  
以下の 2 か所でユーザー名の {user} を必ず置き換えてください。

```bash
cat << EOF > indiwebmanager.service
[Unit]
Description=INDI Web Manager
After=multi-user.target

[Service]
Type=idle
# MUST SET YOUR USERNAME HERE.
User={user}
WorkingDirectory=/home/{user}/indiweb
ExecStart=/usr/bin/pipenv run indi-web -v
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF
```

**Comment by denebola213** [comment]
```sh
$ pipenv run indi-web -v
Traceback (most recent call last):
  File "/home/denebola213/.local/share/virtualenvs/indiweb-3suirynz/bin/indi-web", line 5, in <module>
    from indiweb.main import main
  File "/home/denebola213/.local/share/virtualenvs/indiweb-3suirynz/lib/python3.11/site-packages/indiweb/main.py", line 11, in <module>
    from importlib_metadata import version
ModuleNotFoundError: No module named 'importlib_metadata'
```

以下で解決

```sh
pipenv install importlib_metadata
```

**Comment by denebola213** [comment]
```log
Nov 19 00:22:45 indi pipenv[801]: Traceback (most recent call last):
Nov 19 00:22:45 indi pipenv[801]:   File "/home/denebola213/.local/share/virtualenvs/indiweb-3suirynz/bin/bottle.py", line 995, in _handle
Nov 19 00:22:45 indi pipenv[801]:     out = route.call(**args)
Nov 19 00:22:45 indi pipenv[801]:           ^^^^^^^^^^^^^^^^^^
Nov 19 00:22:45 indi pipenv[801]:   File "/home/denebola213/.local/share/virtualenvs/indiweb-3suirynz/bin/bottle.py", line 2025, in wrapper
Nov 19 00:22:45 indi pipenv[801]:     rv = callback(*a, **ka)
Nov 19 00:22:45 indi pipenv[801]:          ^^^^^^^^^^^^^^^^^^
Nov 19 00:22:45 indi pipenv[801]:   File "/home/denebola213/.local/share/virtualenvs/indiweb-3suirynz/lib/python3.11/site-packages/indiweb/main.py", line 140, in main_form
Nov 19 00:22:45 indi pipenv[801]:     return template(os.path.join(views_path, 'form.tpl'), profiles=profiles,
Nov 19 00:22:45 indi pipenv[801]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 19 00:22:45 indi pipenv[801]:   File "/home/denebola213/.local/share/virtualenvs/indiweb-3suirynz/bin/bottle.py", line 4493, in template
Nov 19 00:22:45 indi pipenv[801]:     TEMPLATES[tplid] = adapter(name=tpl, lookup=lookup, **settings)
Nov 19 00:22:45 indi pipenv[801]:                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 19 00:22:45 indi pipenv[801]:   File "/home/denebola213/.local/share/virtualenvs/indiweb-3suirynz/bin/bottle.py", line 4076, in __init__
Nov 19 00:22:45 indi pipenv[801]:     self.filename = self.search(self.name, self.lookup)
Nov 19 00:22:45 indi pipenv[801]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 19 00:22:45 indi pipenv[801]:   File "/home/denebola213/.local/share/virtualenvs/indiweb-3suirynz/bin/bottle.py", line 4091, in search
Nov 19 00:22:45 indi pipenv[801]:     raise depr(0, 12, "Use of absolute path for template name.",
Nov 19 00:22:45 indi pipenv[801]: DeprecationWarning: Warning: Use of deprecated feature or API. (Deprecated in Bottle-0.12)
Nov 19 00:22:45 indi pipenv[801]: Cause: Use of absolute path for template name.
Nov 19 00:22:45 indi pipenv[801]: Fix: Refer to templates with names or paths relative to the lookup path.
```

https://github.com/knro/indiwebmanager/issues/59#issuecomment-2336327314
